tasks:
  - name: Install Python and dependencies
    init: |
      pyenv install 3.10.7
      pyenv local 3.10.7
      python -m venv venv
      . venv/bin/activate
      pip install -r requirements.txt
