tasks:
  - name: Install Python and dependencies
    init: |
      pyenv install 3.11.1
      pyenv local 3.11.1
      python -m venv venv
      . venv/bin/activate
      pip install -r frozen-requirements.txt
